apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: adelelfar/multi-worker
      ports:
        - containerPort: 9999
        #on this container we are going to create, we wnana expose port 3000 to the outside world
        # why expose? pastly nginx server listens in port 3000