  version: 2.1
  jobs:
    eb-demo:
      docker:
        - image: "cimg/base:stable"
      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Does docker even exist
            command: docker -v
        - run: docker build -t adelelfar/react-test -f ./client/Dockerfile.dev ./client
        - run: docker run -e CI=true adelelfar/react-test npm test
        - run: docker build -t adelelfar/multi-client ./client
        - run: docker build -t adelelfar/multi-nginx ./nginx
        - run: docker build -t adelelfar/multi-server ./server
        - run: docker build -t adelelfar/multi-worker ./worker
        - run: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        - run: docker push adelelfar/multi-client
        - run: docker push adelelfar/multi-nginx
        - run: docker push adelelfar/multi-server
        - run: docker push adelelfar/multi-worker
        

  workflows:
    elastic-beanstalk-workflow:
      jobs:
        - eb-demo

